### ISSUE TITLE
Package build targets - ExcelDnaClean deletes too many output files

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#101]
The ExcelDnaClean build target (in https://github.com/Excel-DNA/ExcelDna/blob/master/Package/ExcelDna.AddIn/tools/ExcelDna.AddIn.targets) deletes all .dna and .xll files in the output directory.

If multiple add-ins are built to the same output directory, only the .dna / .xll files from the last project will remain.

**Comment by govert** [comment]
@caioproiete I don't know if you'd like to have a look at this? It relates to this discussion: https://groups.google.com/d/topic/exceldna/oZZH108Z4FU/discussion

**Comment by govert** [comment]
@caioproiete I think we should look at this issue before the release. Would you perhaps have a chance? 

If it's tricky to work out the file list for the "Clean" case, maybe clean should just leave all the files, or is that terrible?

**Comment by caioproiete** [comment]
@govert That seems simple to resolve. When are you planning to release? I believe I can put some time aside to fix this on March 5th.

**Comment by govert** [comment]
@caioproiete That would be wonderful - thank you!

I definitely want to test this version against the release of VS 2017 first, so no release before mid- to end-March at the earliest.

**Comment by sizzles** [comment]
Hi @govert , @caioproiete  

I had a look at this yesterday, however I ran into a couple of issues

Referencing the project name fixes the above use case. Eg
`      <ExcelDnaFilesToDelete Include="$(TargetDir)**\$(ProjectName)*.dna" />`

However if you have two projects with a shared name:
AddIn1
AddIn12

The build process will delete too many files, as AddIn12 files are also removed.

Another option is to reference the .dna files in the None group `<DnaFiles Include="@(None)"  Condition="'%(Extension)' == '.dna'" />` and use it to build specific file names with 32/64bit and packed suffixes.  

However, this would not clean renamed .dna files eg -> `-AddIn.dna to -MyAddIn.dna `

So, I guess a history of files or a stamped file property that doesn't change on a per project basis might be needed?

Happy to hear your thoughts,

Alex

**Comment by caioproiete** [comment]
Hey @sizzles, thanks for looking into that.

I was hoping we could do something like what you suggested, using something that involved `$(TargetName)*.dna`, etc., but as you point out it would fail in some edge cases.

The "Clean" process [should delete a number of files](https://github.com/Excel-DNA/ExcelDna/blob/master/Package/ExcelDna.AddIn/tools/ExcelDna.AddIn.targets#L65-L67), i.e. any `.dna`, `.xll`, and `xll.config` generated during the build process (and that include the `-packed` versions as well, if exists), and [we only really know the names of these files inside the `CreateExcelAddIn` MSBuild Task](https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs#L117-L118), so with that said, I'm thinking that the way to go about fixing this issue is to write a `CleanExcelAddIn` MSBuild task inside the `ExcelDna.AddIn.Tasks` project, and extract the logic that is used to generate the names of the files, so that both tasks can share the same logic, and have the clean happen via that MSBuild task.

I've put aside a couple of hours to give this a go tomorrow, but if you want to take this one forward today or tomorrow let me know.

**Comment by sizzles** [comment]
Hi @caioproiete ,

No problem, I'll spend some time today looking into a new MSBuild task to see what I can do.

**Comment by sizzles** [comment]
I've put some changes up here: https://github.com/sizzles/ExcelDna

Though still the issue of deleting previously renamed files + further refactoring and simplification of the API, mainly on handling of packed files.

**Comment by govert** [comment]
@sizzles That looks great - thank you!
Do you think you could make a pull request from that branch - that makes it a bit easier for me to incorporate.

**Comment by sizzles** [comment]
@govert  - Sure, should have some time Saturday to do that. More than happy for feedback, to make changes etc etc
