### ISSUE TITLE
Native Async freeze UI

### ISSUE THREAD

**Issue by pmunin** [Excel-DNA/ExcelDna#117]
Native Async does not seems to work asynchronously - it freezes the UI while waiting.
Tried samples - the same story.

```
[ExcelFunction(ExplicitRegistration = true, IsThreadSafe = false)/*regardless if it's marked as threadsafe*/]
public static void _TestNativeAsync([ExcelArgument(AllowReference = true)] object xx, object valueToEcho, int msToSleep, ExcelAsyncHandle asyncHandle)
{
      ThreadPool.QueueUserWorkItem(delegate (object state)
      {
          Thread.Sleep(msToSleep);
          asyncHandle.SetResult(valueToEcho);
      });
}
```
I'm using Excel 2010 x86, .NET 4.6.2

**Comment by govert** [comment]
@pmunin I think it works as expected (as least on my machine).
Excel's native async functions don't allow you to continue working while Excel is calculating. Any click or keyboard activity will cause Excel to suspend the calculation (you'll see 'CALCULATE' in the status bar) and then resume once you've stopped interacting. Calculations of native async functions will however run in parallel, so calling this function in 10 cells will recalculate a lot faster than `10 * msToSleep`.

It can take a second or two for Excel to cancel the calculation once you clicking or press a key.

If you're not sure whether this is the expected behaviour for the native async functions, we can check again with the sample C add-in to check...
