### ISSUE TITLE
"Cannot run macro" issue with Excel 2016

### ISSUE THREAD

**Issue by jamaynor** [Excel-DNA/ExcelDna#133]
Govert,

I recently upgraded to Excel 2016 and an addin I have been working on no longer allows the shortcut key feature in ExcelDna to work. I get the "Cannot run macro" error and have tried everything I have read to fix the problem including:
  - setting Trust Access to the VBA model
  - Enable All macros

I've even recreated a test addin using the updated ExcelDna.Addin module from Nuget. Mu AddinController file looks like:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDna.Integration;

namespace ExcelDna_Test
{
    class AddinController : IExcelAddIn
    {
        public void AutoClose()
        {
        }

        public void AutoOpen()
        {
            XlCall.Excel(XlCall.xlcOnKey, "^H", "HelloDna");
            HelloDna();
        }

        [ExcelCommand]
        public static void HelloDna()
        {
            System.Windows.Forms.MessageBox.Show( "Hello Dna");
        }

    }
}

and my ExcelDna_Test-Addin.dna file looks like:
<DnaLibrary Name="ExcelDna-Test Add-In" RuntimeVersion="v4.0">
  <ExternalLibrary Path="ExcelDna-Test.dll" ExplicitExports="false" LoadFromBytes="true" Pack="true" ExplicitRegistration="false" />
  
  
  
  

</DnaLibrary>

Is there a new bug for Excel 2016? How can I get shortcuts to work?

thanks,
Jeremy

**Comment by govert** [comment]
Hi James,

The class containing your macros and UDF functions must be “public” for Excel-DNA to register them with Excel. Set AddInController to “public” and the “HelloDna” macro will be registered with Excel and everything including the shortcut you set will work as expected.

Note that you could also implement the shortcut by adding it to the ExcelCommand attribute:

    public class AddinController : IExcelAddIn
    {
                 ……….

        [ExcelCommand(ShortCut ="^H")]
        public static void HelloDna()

                 ……….


An oversight I made long ago allows the class that implements IExcelAddIn to be non-public and Excel-DNA will still load and execute it. I’ve decided for backward compatibility, and because of various published samples, not to make a change to the more obvious arrangement where the IExcelAddIn class must be public too (like the UDF-containing classes).

-Govert

**Comment by govert** [comment]
Oh  sorry – I see now that you’re “Jeremy” and not “James”.…

-Govert

**Comment by govert** [comment]
@jamaynor 

The class containing your macros and UDF functions must be “public” for Excel-DNA to register them with Excel. Set AddInController to “public” and the “HelloDna” macro will be registered with Excel and everything including the shortcut you set will work as expected.

Note that you could also implement the shortcut by adding it to the ExcelCommand attribute:

```c#
    public class AddinController : IExcelAddIn
    {
        // ……….

        [ExcelCommand(ShortCut ="^H")]
        public static void HelloDna()

        // ……….
    }
```

An oversight I made long ago allows the class that implements IExcelAddIn to be non-public and Excel-DNA will still load and execute it. I’ve decided for backward compatibility, and because of various published samples, not to make a change to the more obvious arrangement where the IExcelAddIn class must be public too (like the UDF-containing classes).

**Comment by jamaynor** [comment]
That worked like a charm Govert. Thank you very much.
