### ISSUE TITLE
UnInstall-Package ExcelDna.AddIn fails

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#140]
I get the following output when trying to uninstall the ExcelDna.AddIn package:

```
PM> UnInstall-Package ExcelDna.AddIn


Attempting to gather dependency information for package 'ExcelDna.AddIn.0.34.6' with respect to project 'TestRtdServer', targeting '.NETFramework,Version=v4.0'
Resolving actions to uninstall package 'ExcelDna.AddIn.0.34.6'
Resolved actions to uninstall package 'ExcelDna.AddIn.0.34.6'
Executing script file 'C:\Work\ExcelDna\UserSamples\XXX\packages\ExcelDna.AddIn.0.34.6\tools\uninstall.ps1'
Starting ExcelDna.AddIn uninstall script
	Renaming -AddIn.dna file
	Clearing Debug start settings
Removing build targets from the project
Completed ExcelDna.AddIn uninstall script
Removed package 'ExcelDna.AddIn.0.34.6' from 'packages.config'
Successfully uninstalled 'ExcelDna.AddIn.0.34.6' from TestRtdServer
Removing package 'ExcelDna.AddIn.0.34.6' from folder 'C:\Work\ExcelDna\UserSamples\XXX\packages'
Access to the path 'C:\Work\ExcelDna\UserSamples\XXX\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDna.AddIn.Tasks.dll' is denied.
Access to the path 'ExcelDna.AddIn.Tasks.dll' is denied.
Removed package 'ExcelDna.AddIn.0.34.6' from folder 'C:\Work\ExcelDna\UserSamples\XXX\packages'
Executing nuget actions took 926.03 ms
Time Elapsed: 00:00:00.9683776
One or more packages could not be completely uninstalled: 'C:\Work\ExcelDna\UserSamples\XXX\packages\ExcelDna.AddIn.0.34.6'. Restart Visual Studio to finish uninstall.
```

**Comment by caioproiete** [comment]
@govert This is a well-known issue with any NuGet package that uses custom MSBuild tasks. The MSBuild process(es) keep running even after the build finishes, locking the assembly, and when a package is uninstalled, NuGet is not able to delete the MSBuild task assembly because of the locking.

As the message says, NuGet is flagging those files for deletion and will do so on the next restart of Visual Studio.

We can accept the default behavior and advise users to restart Visual Studio after uninstalling the package, as per the the error message:

> One or more packages could not be completely uninstalled: 'C:\...'. Restart Visual Studio to finish uninstall.

Or we can try to find a workaround that would involve changing our build process in the `.targets` to copy the Tasks assembly to a temporary folder as the first build step, and then load the Tasks assembly dynamically in the next build step.

**Comment by govert** [comment]
@caioproiete Oh - I didn't know about this. Do you have some link or reference to a discussion?

I don't  think we should worry about it then. With the whole install.ps1 / PackageReference debacle, I think we can wait for the VS / MSBuild  / NuGet interactions to stabilize a bit before making changes. It seems they're still figuring where to go with this.

**Comment by govert** [comment]
I'm closing this for now - not our problem.
