### ISSUE TITLE
Replace the post-build commands with custom MSBuild tasks + custom build target

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#17]
As discussed in #15 we should write one or more custom MSBuild tasks, ship them into one assembly, and have a custom build target to run them as part of the build.

These MSBuild tasks would be responsible for copying the XLL to the bin folder, as well as running ExcelDnaPack based on a conditional compilation symbol.

**Comment by govert** [comment]
I think this should be done with custom MSBuild targets, but using the ExcelDnaPack binary rather than a separate library of build tasks.

Is there any reason not to implement the build targets that way? Keeping the ExcelDnaPack as an executable that does the extra work means that other approaches to build automation are still supported.

**Comment by CaioProiete** [comment]
I think we should have both. A custom build target that uses an MSBuild task to perform the job (which would be included in the NuGet package), and a separate utility (ExcelDnaPack) distributed outside of the NuGet package, for people who want to run it via command-line.

Both the ExcelDnaPack utility and the MSBuild task assembly would share the exact same code, but with just different entry points.

I think from a build perspective, it is better to have a tighter integration with MSBuild vs. spinning up a new process every time you build (which is harder to guarantee that it will actually stop, and it is much harder to raise proper error messages and fail the build when a validation fails or something goes wrong - e.g. unable to patch the version because the attribute is missing in the .dna file).

ps: I'm sure I'm being a little pedantic - sorry about that :)

**Comment by caioproiete** [comment]
This has been fixed with merging of #27
