### ISSUE TITLE
compatible issue

### ISSUE THREAD

**Issue by alvincheng75** [Excel-DNA/ExcelDna#236]
The first time I install exceldna in visualstudio2017 , I meet the following issue:
ExcelDna.Integration 0.34.6 is not compatible with uap10.0.10586 (UAP, Version=v10.0.10586)！

**Comment by alvincheng75** [comment]
install exceldna in nuget

**Comment by caioproiete** [comment]
@alvincheng75 That is by design. Currently Excel-DNA is only compatible with **`Windows Desktop, Class Library (.NET Framework)`** projects. It looks like you created a **`Windows Universal, Class Library (Universal Windows)`** project.

Make sure you create the correct type of project:

![image](https://user-images.githubusercontent.com/177608/55126577-ce45f400-50e3-11e9-8308-4c4d543e7220.png)
