### ISSUE TITLE
Improve impl. of XlCallImpl.TryExcelImpl12() method

### ISSUE THREAD

**Issue by mvorisek** [Excel-DNA/ExcelDna#245]
The current impl of `XlCallImpl.TryExcelImpl12()` method
https://github.com/Excel-DNA/ExcelDna/blob/2aa1bd9afaf76084c1d59e2330584edddb888eb1/Source/ExcelDna.Loader/XlCallImpl.cs#L140
is slow. It creates a lots of objects for every call.

The exec. time is critical as this is a core function that is called in every UDF call when RTD is used or for example if sheet reference is queried.

Compare (about 4.5 us / call):
```
XlCall.Excel(XlCall.xlfCaller);
```
vs. much faster (about 1.25 us / call)
```
XlCallImpl.GetCallerSheetId12();
```

The same improvement is expected for RTD which uses `XlCall.Excel()`
https://github.com/Excel-DNA/ExcelDna/blob/2aa1bd9afaf76084c1d59e2330584edddb888eb1/Source/ExcelDna.Integration/ExcelRtd.cs#L176

So the impl. of XlCallImpl.TryExcelImpl12() method should be optimized as much as possible.

**Comment by govert** [comment]
You are certainly right that there is room for optimization here. The whole marshalling interface to the C API is due for a re-look.

The relevant code, and the Excel implementation against which this runs, is not easy to work with due to the rules of memory management in the C API, and the fact that this function needs to be recurrent on a single thread. So I'd be careful in making or accepting changes here, especially while we don't have a good testing framework.

If you want to work on this, I suggest a starting point is figuring out a good testing approach for the marshaling, that allows one to monitor correctness, guard against memory leaks and then check performance.

**Comment by mvorisek** [comment]
Closing as the performance example is not optimal, as the `XlCall.Excel(XlCall.xlfCaller);` calls the `XlCallImpl.GetCallerSheetId12();` inside, so the room to improve is not that large.
