### ISSUE TITLE
Support for concrete inheritance of Ribbon classes

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#247]
As per described in [this message in the mailing-list](https://groups.google.com/forum/#!topic/exceldna/eZ14oowshkk), in order to use inheritance with `ExcelRibbon`-derived classes, the base class must:

* Be marked as `abstract`
* Have the a `ComVisible` attribute set to `true` i.e. `[ComVisible(true)]`

---

![image](https://user-images.githubusercontent.com/177608/58598263-e6f09880-8251-11e9-85e3-a4c4ac7835c6.png)

In the example above, the [current design](https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Integration/AssemblyLoader.cs#L337) will load only the least-derived concrete class, meaning:

* `RibbonA` is **_not_** loaded :x:, and `BaseRibbon` **_is_** loaded :x:
* `RibbonB` **_is_** loaded :heavy_check_mark:, and `BaseAbstractRibbon` is **_not_** loaded :heavy_check_mark:

I believe the expectation would always be that `RibbonA` **_is_** loaded, whilst `BaseRibbon` is **_not_** loaded.

Thoughts?

Is it worth fixing in the main codebase? Or should we outsource this to a separate "`RibbonRegistration`" helper library, similar to what is done today with registration of functions via the [`Registration`](https://github.com/Excel-DNA/Registration) library?

**Comment by govert** [comment]
I agree that loading RibbonA make more sense, however I'm not sure how easy the discovery is during the assembly loading examination, since RibbonA might be in a different assembly to BaseRibbon. I suspect it will be convoluted to implement into the current assembly scanning, but don't object to the changed behaviour in principle.

Reasons why it might not be worth the effort to fix: 
Would it be common to make a BaseRibbon that must both be loadable on its own (i.e. cannot be marked abstract) and that must serve as a base class for others? That seems like an unusual edge case which can be trivially worked around in the user's add-in by making BaseRibbon abstract, and then having another 'empty' but concrete class that derived from it to get instantiated. In the support discussion that initiated the issue, it was very easy to resolve this way to the add-in developer's satisfaction.

Finally, it's certainly possible to make and load custom ribbon classes that do not derive from ExcelRibbon but rather from ExcelComAddIn, and are explicitly loaded by `ExcelComAddInHelper.LoadComAddIn`. So the add-in itself or a utility library could bypass the built-in `ExcelRibbon` support.

So I don't think this issue is worth bothering with.

**Comment by caioproiete** [comment]
Closing as `wontfix`.
