### ISSUE TITLE
RTD async functions freeze excel

### ISSUE THREAD

**Issue by andrewbridge** [Excel-DNA/ExcelDna#255]
Hi there,

I've been working with Excel DNA to produce an excel plugin that predominantly interfaces with my company's web API (via a C# client that just wraps calls via an HTTP client) to provide modelled financial data (generally with the end goal of plotting the returned data series on charts).

In general, we've had a lot of success. However, today I ran into a scenario where I managed to lock up Excel by making successive requests to a particular async function.

Assuming the following changes in my spreadsheet:

**Step 1**

|   | A         | B                         |
|---|-----------|---------------------------|
| 1 | 13-Aug-19 | =my_long_running_func(A1) |

**Step 2**

|   | A         | B                         |
|---|-----------|---------------------------|
| 1 | 09-Aug-19 | =my_long_running_func(A1) |

**Step 3**

|   | A         | B                         |
|---|-----------|---------------------------|
| 1 | 13-Aug-19 | =my_long_running_func(A1) |

`my_long_running_func` receives 3 calls. To the first two, it returns `#N/A` as expected, but the third never returns after making the API call. Excel locks up and control is only returned when the API call times out several minutes later, with an exception: `A task was canceled.`.

While the long running API call and probably the exception thrown are both nothing to do with Excel DNA and things that we need to fix too, I was wondering if you'd be able to suggest any reason why Excel would lock up despite us running these calls as async functions. The common theme I can see is the parameter change back to a value the function has already seen (`13-Aug-19`) while the async function is still in flight.

`my_long_running_func` roughly looks like:

```c#
        [ExcelFunction(Name = "my_long_running_func", Description = "Runs for a long time")]
        public static object LongRunningFunc(
            [ExcelArgument(Name = "Date")] DateTime date)
        {
            var parameters = new object[] { date };
            return ExcelAsyncUtils.Run(
                "LongRunningFunc",
                parameters,
                delegate
                {
                    // ApiRequest is an object provided by the API client
                    var request = new ApiRequest
                                  {
                                      Date = date,
                                  };
                    var response = GetApiClient().CalculateModel(request).GetAwaiter().GetResult();
                    // Parse response and put it into an object[,]; the code never reaches this point
                    return output;
                });
        }
```

We have also tried using https://github.com/StephenCleary/AsyncEx which has helped us out in a few scenarios where the `.GetAwaiter().GetResult()` pattern sent us into deadlock. But switching `var response ...` to `var response = AsyncContext.Run(() => GetApiClient().CalculateModel(request))` does not change the behaviour described.

I've been looking through `ExcelDna.Integration/ExcelRtdObserver.cs` as I was wondering if your caching mechanism was waiting on the result of the async function (which would mean further calls with matching parameters could potentially be blocked(?)), but I can't see any evidence of that.

Apologies, I'm aware of how vague a problem this is, but I was hoping that someone with more expertise might see an error in my use of the library or might be able to provide an explanation on how the function ultimately gets called, and in turn provide some clues as to why our API client is blocking the main thread.

Any input would be hugely useful as the library has, thus far, worked marvellously.

**Comment by govert** [comment]
@andrewbridge Would you be able to make a small standalone project that produces this behaviour? I can then give debugging it a go.

As it is your `ExcelAsyncUtils` or API client could be doing anything . . .
The only thing I can think of immediately is that your implementation tries to get back to the main thread somewhere (e.g. by making a COM call back to Excel from another thread). 

The implementation of the real `ExcelAsyncUtil.Run` just schedules the work on the .NET ThreadPool, and while that might lead to slow execution due to the small initial number of threads and slow growth heuristic, it should not deadlock Excel.

In general I expect the RTD-based async to work quite reliably, as it has been in widespread use for a while.

**Comment by andrewbridge** [comment]
@govert sure, I'll give this a go. I find it quite hard to reproduce in debug mode, but I'll see if I can work something out that consistently produces this behaviour and if not I'll work back from there in my current project.

Re: COM call backs from another thread, would a call to `XlCall.Excel(XlCall.xlfCaller)` count? I don't _think_ we make this call inside the async function anywhere, but it'd be one for me to watch for as it is used quite a lot in some of the utility functions I've written.

One of the other things we do in the codebase is wrap the original async function provided in another to allow easier error handling and logging. It looks something like this:

```C#
        private static ExcelFunc WrapFunc(ExcelFunc asyncFunc)
        {
            return () =>
            {
                try
                {
                    return asyncFunc();
                }
                catch (Exception e)
                {
                    if (e.Message == "AUTH_ERROR")
                    {
                        // Return human friendly error if API auth fails
                        return new ExcelCommandError(Language.Utils_RunAsync_auth_unsuccessful);
                    }

                    Logger.Error(e);
                    return new ExcelCommandError(e.Message);
                }
            };
        }
```

Is there anything about that kind of practice or the way the original function is being invoked that would cause issues?

**Comment by govert** [comment]
@andrewbridge Alternatively you can try to reproduce the problem using one of the RTD sample projects from here: https://github.com/Excel-DNA/Samples/tree/master/RtdClocks and see if you can recreate the issue.

**Comment by govert** [comment]
I don't think your extra `ExcelFunc` wrapper is a problem.

**Comment by govert** [comment]
xlfCaller won't work from inside the async setting or another thread. You have to call it when the outermost wrapper function is called, and capture the result into a local for later use.

**Comment by andrewbridge** [comment]
@govert Apologies for the delay

I've put together a relatively simple implementation of an ExcelDNA add-in which works with an API client (based on an HTTP client and the [reqres.in service](https://reqres.in)) to retrieve data from an API via multiple UDFs (`hangexcel_short`, `hangexcel_med`, and `hangexcel_long` which all take a string and a date as parameters)

While I wasn't able to get Excel to freeze, I did notice that calls were still appearing to wait behind long running calls (reqres.in allows calls to delay return with a `?delay` query string). Just to check this wasn't the fault of the API client, I also set up `hangexcel_spam`, which takes the same parameters and launches a large number of API calls at once per call to the UDF. These did not seem to show the same behaviour.

I've added screencaptures below of my actions in Excel and a network monitor filtering just calls to the reqres.in host, using both variants of call. I've also uploaded the project to [andrewbridge/HangingExcelDNA](https://www.github.com/andrewbridge/HangingExcelDNA) which includes the Excel file I used to produce the captures.

It's not quite the original issue I reported, but I think these conditions did contribute to the issue when it was built and packed in Release mode (it was a user that reported the issue rather than one I found myself). I'm also aware that hammering the UDFs multiple times before they return is probably a little extreme, but again it was an impatient user doing exactly that kind of hammering that found the problem in the first place.

Do you have any suggestions that would mean I could run these long running calls without blocking further calls from other UDFs? As usual, any help or information would be hugely appreciated!

## Multiple requests made via multiple UDF calls
_Requests appear to be blocked by longer running requests_

[Streamable version for playback control](https://streamable.com/ujhr1)
![blocked-requests](https://user-images.githubusercontent.com/2941908/63532603-f0ad3380-c502-11e9-92e1-2b77d8a2a3d8.gif)

## Multiple requests made via single UDF
_Requests appear to be called instantly, even with repeated calls to the UDF_

[Streamable version for playback control](https://streamable.com/8jpxs)
![non-blocked-requests](https://user-images.githubusercontent.com/2941908/63534460-2522ee80-c507-11e9-8510-75262a0e2a83.gif)

**Comment by govert** [comment]
@andrewbridge You're seeing the default behaviour of the .NET ThreadPool when Tasks are enqueued. Basically the ThreadPool starts small, and with your current code (basically the default Excel-DNA async API) your slow Tasks are using up the initially small ThreadPool quickly - every outstanding delegate uses up a ThreadPool thread until it is complete.

A simple test to confirm this is to make the initial ThreadPool large by adding a call like this when your add-in is loaded:
```
    System.Threading.ThreadPool.SetMinThreads(200, 200);
```

This will make sure your Tasks enqueue quickly (thus making the outgoing calls quickly). But that's not the optimal use of the ThreadPool or the .NET Task-based infrastructure .

The better approach is to use the Task-based async/await throughout - using async Tasks as supported by the HttpClient class should not use a ThreadPool except possibly for the 'fast' synchronous completion code. To do this means you need to replace `ExcelAsyncUtil.Run` with another implementation that is a Task-based wrapper on top of `IExcelObservable`.

I have an extension library called `[ExcelDna.Registration](https://github.com/Excel-DNA/Registration)` that does all of this automatically (or has some code like AsyncTaskUtil.cs to help you implement it yourself). This means you can change your exported function from the HangingExcel sample to look like this:

```
        [ExcelFunction(Name = "hangexcel_long", Description = "Do a long async call")]
        public static async Task<object> LongRun(string name, DateTime when)
        {
            var request = new DetailsRequest { Name = name, Date = when };
            var client = new FakeCallsClient();
            // Vary long calls
            var response = await (longCallCount % 2 == 0 ? client.GetColoursTooSlowlyAsync(request) : client.GetColoursVerySlowlyAsync(request));
            longCallCount++;
            return "Hello " + name + " on " + when.ToShortDateString();
        }
```

Note that is is an `async` / `await` function returning `Task<T>` directly. The magic is in the Registration library, which is called in an `AutoOpen` helper:
```
    public class AddIn : IExcelAddIn
    {
        public void AutoOpen()
        {
            ExcelRegistration.GetExcelFunctions()
                             .ProcessAsyncRegistrations(nativeAsyncIfAvailable: false)
                             .RegisterFunctions();
        }

        public void AutoClose()
        {
        }
    }
```

I've made a pull request against your test project that should compile and give you the parallel requests you expect.

**Comment by andrewbridge** [comment]
@govert ah brilliant, yes, it did feel a bit wrong forcing async'able methods to run synchronously!

This is amazing, I'll have a play about with your updates and check I understand what's going on, then come back if I have any further questions.

In the meantime, thank you for the help! Between the library itself and the various threads you've replied to that littered across Google, I'm hugely appreciative!

**Comment by govert** [comment]
Cool @andrewbridge - it's a pleasure. 
And don't forget to click on the " ❤️ Sponsor " button above 😉

**Comment by andrewbridge** [comment]
Hi @govert, 

I've finally had some time to look at this. Having played around with it, it's certainly a great improvement!

I notice that on changing the date in the example, the user loses interactively for a second or two initially. This is presumably because a large number of functions are updating at once?

I see that this also removes the pattern of passing an async function to the library. The set up in my main codebase makes use of this pattern in order to wrap the async function further in order to provide my own logging and error handling, as well as passing back an alternative holding state to `#N/A`.

What would be your suggestion for adding this kind of additional boilerplate around functions? Is there an alternative to `ExcelAsyncUtil.Run`? I see that in your implementation you've used [ProcessAsyncRegistrations](https://github.com/Excel-DNA/Registration/blob/master/Source/ExcelDna.Registration/AsyncRegistration.cs#L30) which appears to provide a global wrapper at launch and uses `WrapMethodRunTask` in turn, is this a preferred pattern that I can either tap into or mimic with my additional wrapper code?

**Comment by govert** [comment]
@andrewbridge The [ExcelDna.Registration](https://github.com/Excel-DNA/Registration) extension library is meant to help create such wrappers. The implementation is open and you can use it or take from it whatever parts you'd like.
The wrappers for `Task<T>` based async functions avoid `ExcelAsyncUtil.Run` by building on the lower-level `IExcelObservable` implementation.

**Comment by andrewbridge** [comment]
Excellent, this actually looks like a much nicer pattern, thank you.

I think I probably just need to try it and find out, but does this method take away all the automatic processing I'm currently expecting? Such as parameter type conversion and async method caching? Or are the examples just suggesting methods of overriding that default behaviour?

**Comment by andrewbridge** [comment]
Ended up finding ExcelDna.Registration works very well for my purposes, including the wrapping of async functions and wrapping error handling etc round functions. Thanks again, closing.

**Comment by terryaney** [comment]
> xlfCaller won't work from inside the async setting or another thread. You have to call it when the outermost wrapper function is called, and capture the result into a local for later use.

Is there no work around for this?  In my ExcelDNA add-in I have a ribbon button that runs an async function and inside the implementation of that it makes a couple calls to xlfCaller to get range information (sheet, document, etc.)

**Comment by govert** [comment]
Hi @terryaney - thank you for signing up as a sponsor!

`xlfCaller` is used for a C API call which can only be made in the context of a UDF called from the Excel sheet. The problem with an async function is that the inside part of the function is not really being called from Excel, but is called from the ThreadPool to do the work. So the `xlfCaller` cannot be made in this context. The workaround I explained above is to make the xlfCaller call in the entry point to the function, and capture the result before making setting up the async part of the function.

If you are running some code from a ribbon handler (I think this is what you are doing when you say you have a button that 'runs an async function') you have a few problems.

First is that there is not 'caller' for a UDF in this context, since it is not called from a formula on a worksheet. There is still an 'active cell' which might be what you want to use. Since you are not in a function context when running code from a ribbon button, you have access to the full Excel COM object model (via `ExcelDnaUtil.Application`), so you could get the ActiveCell that way and use it from there.

A further complication with the async case is that you shouldn't use the COM object model from threads other than the main thread. This means you can't use the result of `Application.ActiveCell` (which is a `Range` object) in the async part of the code (since this runs on some other thread). So you have to gather whatever information you need before the aync part starts, and then if you want the ribbon button press to change the sheet, you have to get some code to run as a macro after the async part is complete. The mechanism to do this is to call `ExcelAsyncUtil.QueueAsMacro` with (a delegate to) the code you want to run, and this will execute back on the main thread. Keen in mind that the active cell might have changed in the mean time between the press of the button and the completion of the async part.

Overall, you can see things get complicated in this case, and need some more thought. But it's not just a small Excel limitation with an easy workaround.

**Comment by terryaney** [comment]
Thanks.  Will see what sort of solution I can come up with.  As an FYI, I slightly misspoke above I think because all my code was working with `xlfCaller` before a recent change.

We originally were a VBA addin, and thus part of the 'processing' was calling a known `ProcessWorkbook` method.  Since changing to ExcelDNA, that method was simply updated to:

```
Function ProcessWorkbook() As Long
On Error GoTo Err_Trap

    Dim btr As Object: Set btr = CreateObject("BTR.Extensibility.Excel.VBAHelpers")
    Dim start As Single: start = Timer

   Call btr.ProcessMacros

   ProcessWorkbook = 0
   Debug.Print "Time Elapsed = " & (Timer - start)

Exit Function

Err_Trap:
    ProcessWorkbook = Err.Number
    Debug.Print Err.Description
End Function
```

But our AddIn does have a ribbon button that kicks this off so user doesn't have to do it themselves:

```csharp
public void ProcessWorkbook()
{
	try
	{
		var activeWorkbook = application.ActiveWorkbook;
		var ceName = activeWorkbook != null ? $"'{activeWorkbook.Name}'!" : null;
		var result = (int)application.Run( ceName + "ProcessWorkbook" );

		if ( result != 0 )
		{
			throw new ApplicationException( "The macro returned: " + result );
		}
		MessageBox.Show( "The ProcessWorkbook() macro ran with no errors.", "ProcessWorkbook Macro", System.Windows.Forms.MessageBoxButtons.OK, System.Windows.Forms.MessageBoxIcon.Information );
	}
	catch ( Exception ex )
	{
		ExcelDna.Logging.LogDisplay.WriteLine( "\r\nThe ProcessWorkbook() macro failed.\r\n\r\nDetails: " + ex.Message );
	}
}
```

As you can guess, `BTR.Extensibility.Excel.VBAHelpers.ProcessMacros` is where I make my `xlfCaller` calls.

Originally I had:

```csharp
public void ProcessMacros()
{
	var macroProcessor = new VBAMacroProcessor( ApplicationEx.ActiveWorkbook.Name );
	var helpersCalcEngine = new VBAMacroProcessor( CalcEngines.HelpersCalcEngineName );

	try
	{
		macroProcessor.ProcessMacros( helpersCalcEngine );
	}
	catch ( System.Exception ex )
	{
		ExcelDna.Logging.LogDisplay.Clear();
		ExcelDna.Logging.LogDisplay.WriteLine( "*****ProcessMacros Problem*****" );
		ExcelDna.Logging.LogDisplay.WriteLine( "\t" + ex.Message );
		ExcelDna.Logging.LogDisplay.Show();

		throw;
	}
}
```

However, inside our macro processing we introduced a feature to call some Web API endpoints and calling those with `async\await` caused me to go 'async all the way up' and in this method I now have:

```csharp
// https://stackoverflow.com/a/9343733/166231
Task.Run( async () => await macroProcessor.ProcessMacrosAsync( helpersCalcEngine ) ).GetAwaiter().GetResult();
```

Unfortunately, the number of `xlfCaller` functions is much greater/imbedded than I thought.  So I'll have to try and figure something out as my level in `async\await` is admittedly pretty low.  Is it possible to assign a `Func<>` outside the `Task.Run` and call back into that and be 'working on correct thread'?  I'll try...

**Comment by govert** [comment]
I do have some questions:
* Where are you trying to get the caller information - I don't see that in the code?
* What is the caller intended to be when the macro is run, since there is no calling cell for the function?
* What do you do with the caller information?

**Comment by terryaney** [comment]
I wrote this code/migration several years ago (you probably remember several issues you've helped me tackle)...so, I'm wondering if I could re-write all my `xlfCaller` stuff with COM Excel objects.  I'm thinking I used the C API stuff to try and make it as fast as possible vs having some functionality missing from COM.

As to how I'm using it, mostly it is to get cell references.  For example, above where I do `new VBAMacroProcessor( ApplicationEx.ActiveWorkbook.Name )` I pass in the current workbook name and store for later use.  Then, inside my processor, I do something like this (Disclaimer: ProcessMacrosAsync below is a generic method where the 'processor' is either ExcelDNA Addin or a server side SpreadsheetGear component, that's why the code may seem a little weird):

```csharp
public virtual async Task ProcessMacrosAsync( MacroProcessor<TReference> helpersCalcEngine )
{
	var macros = TryGetReference( "RBLeMacro" );
	... more code using the 'macros' reference ...
}

// VBAMacroProcessor
public override ExcelReference TryGetReference( string address ) => ApplicationEx.TryGetWorkbookReference( workbookName, address );

// ApplicationEx
public static ExcelReference TryGetWorkbookReference( string workbookName, string address )
{
	var excelAddress = address.GetExcelAddress();

	var hasSheet = !string.IsNullOrEmpty( excelAddress.Sheet ) && excelAddress.Sheet != ( workbookName ?? ActiveWorkbook.Name ); /* global range if so */
	if ( !hasSheet )
	{
		// Assuming if no sheet provided, they mean the 'active' sheet
		var sheetName = (string)XlCall.Excel( XlCall.xlfGetWorkbook, (int)GetWorkbookType.ActiveSheet, workbookName );

		excelAddress.Sheet = sheetName;
	}

	var addressWorkbook = excelAddress.Workbook ?? workbookName;
	var workbookNameSyntax = !string.IsNullOrEmpty( addressWorkbook ) ? $"[{addressWorkbook}]" : null;

	var fullAddress = $"='{workbookNameSyntax}{excelAddress.Sheet}'!{excelAddress.Address}";
	var reference = XlCall.Excel( XlCall.xlfEvaluate, fullAddress ) as ExcelReference;

	return reference;
}
```

**Comment by govert** [comment]
So when you say 'xlfCaller' you just mean using the C API and the various xlfXXX and xlcXXX methods, and not specifically `xlfCaller`?

You could replace these calls with COM object model calls, but that would lead to other problems due to the threading issue - you cannot safely use the C API or the COM object model from another thread (i.e. inside an async context). This means your `TryGetWorkbookReference` code should always run on the main thread, however you implement it.

**Comment by terryaney** [comment]
Yes, I guess just C API calls.  Putting `TryGetWorkbookReference` on main thread...is that possible?  I tried the `Func<>` test I mentioned above (outside the `Task.Run` just as a captured variable) and the C API calls failed there too.

**Comment by govert** [comment]
> Putting TryGetWorkbookReference on main thread...is that possible? 
You just have to call it directly from the ribbon callback, before you start the async work.
