### ISSUE TITLE
Excel-DNA.Interop vs background threads

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#265]
It seems that calls to COM interop interfaces or methods from background threads often finish without problems but result in Excel crashing in random ways some time later; I wonder if there is any way to make Excel-DNA.Interop throw an exception immediately when it's called from any thread besides the main thread?

**Comment by garethhayter** [comment]
I always access the Application object via my own property, where I store the thread ID of the UI thread, and compare the running thread id with that, throwing an exception when they don’t match, as this means it’s being accessed from a non-UI thread.

 

This check can be wrapped in an “#if DEBUG” pre-processor directive so that it is not checked in release mode – you should be finding issues at dev time.

**Comment by govert** [comment]
One problem is that you might make the `ExcelDnaUtil.Application` call to get the Application object on the main thread, then store it is some variable that you access and use from another thread (even implicitly by capturing a COM object in a delegate).

**Comment by fandrei** [comment]
@govert agreed. And even worse, same problem applies to any other interface that may be obtained from the API and stored somewhere, explicitly or implicitly.

**Comment by fandrei** [comment]
@govert by the way is it open source?

**Comment by fandrei** [comment]
@caioproiete do you know whether ExcelDna.Interop is open source?

**Comment by caioproiete** [comment]
@fandrei **No, `ExcelDna.Interop` is not open-source**. The assembly is the equivalent to the one auto-generated by Visual Studio when you add a COM reference to `Microsoft Excel (version) Object Library`.

![image](https://user-images.githubusercontent.com/177608/67920094-a17a2380-fb81-11e9-9cad-77b281f1989c.png)

**Comment by govert** [comment]
The interop assemblies in `ExcelDna.Interop` match Excel 2010. The binaries are from the Primary Interop Assemblies redistributable from Microsoft, but can be re-created by running [TlbImp](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-generate-primary-interop-assemblies-using-tlbimp-exe) on the Office .tlb type library definitions.

As far as I know, it's not quite possible to create the same interfaces using C# code that wraps the COM calls internally (and can thus do something like check the threads before forwarding the calls). Some magic in the IL or the way the PIA assembly is referenced means the real PIA is treated differently when referencing it, allowing some extra features.

[NetOffice](https://github.com/NetOfficeFw/NetOffice) is a wrapper assembly for the COM in C#, and was useful before C# / .NET 4. (And might be again if .NET 5 still does not have the C# / .NET 4 [dynamic support for COM](https://github.com/dotnet/coreclr/issues/24246) leaving it's COM interop where .NET Framework 2.0 /C# 3 was in 2008.)

**Comment by govert** [comment]
You should note that being on the main thread is necessary but not sufficient evidence to mean it's safe to make reliable COM calls. Calling the COM object model from the main thread in a context where COM calls are not handled, often results in COM errror `0x800A03EC` (which I've seen documented as `NAME_NOT_FOUND`).

**Comment by fandrei** [comment]
@govert I see.

> Calling the COM object model from the main thread in a context where COM calls are not handled, often results in COM errror 0x800A03EC (which I've seen documented as NAME_NOT_FOUND).

What context can this be?

**Comment by govert** [comment]
@fandrei I answered your question here: https://github.com/Excel-DNA/ExcelDna/issues/269#issuecomment-549017994

**Comment by fandrei** [comment]
@govert I see, thanks.

**Comment by augustoproiete** [comment]
As of ExcelDna v1.1 when debugging an add-in, we check if `ExcelDnaUtil.Application` is being called from a thread that is not the main thread, and throw an exception.

![image](https://user-images.githubusercontent.com/177608/68067390-e5595e00-fd24-11e9-87d6-2d2750052f3d.png)

Exception is only raised if the add-in is being debugged (i.e. debugger is attached). This is similar what happens when controls are updated from a non-UI thread in Windows Forms or WPF apps.
