### ISSUE TITLE
Create an .xsd file for the .dna files

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#28]
Creating an .xsd schema file for the .dna files should lead to an improved editing experience in Visual Studio.

**Comment by CaioProiete** [comment]
+1

It will be great to have intellisense for .dna files within Visual Studio.

I also think once we have the .xsd, there's an opportunity to validate the .dna against the .xsd as part of the build - *hint* *hint* another MSBuild task :)

**Comment by konne** [comment]
+1

**Comment by jimfoye** [comment]
I just followed the instructions and downloaded the ExcelDna.DnaLibrary.xsd and added it to my project, and added the xmlns attribute to the DnaLibrary tag. This does result in intellsense, but at runtime the XLL fails  to load:

There is an error in XML document (1, 2).
<DnaLibrary xmlns='http://schemas.excel-dna.net/addin/2018/05/dnalibrary'> was not expected.
Initialization [Error] No Dna Library found.

Also, the instructions talk about a nuget package for schemas, but that package does not exist.

**Comment by govert** [comment]
Support for the xmlns attribute in the .dna file will only come with the next Excel-DNA release v0.35. I'll try to push an updated beta version over the next few days.

On 24 May 2018, at 19:02, Jim Foye <notifications@github.com<mailto:notifications@github.com>> wrote:


I just followed the instructions and downloaded the ExcelDna.DnaLibrary.xsd and added it to my project, and added the xmlns attribute to the DnaLibrary tag. This does result in intellsense, but at runtime the XLL fails to load:

There is an error in XML document (1, 2).
was not expected.
Initialization [Error] No Dna Library found.

Also, the instructions talk about a nuget package for schemas, but that package does not exist.

**Comment by caioproiete** [comment]
@jimfoye That error is expected and [has been fixed in the code](https://github.com/Excel-DNA/ExcelDna/commit/241e09235c7c3c29d743b016254fd84b65aeb494), but has not yet been released. It will come with Excel-DNA v0.35 expected to ship in a few days.

If you want to use IntelliSense right now, you'll have to copy the `.xsd` file(s) to the Visual Studio Schema Cache on your machine by following the instructions below:

* [Install globally to all projects on your machine (manually)](https://github.com/Excel-DNA/ExcelDna/tree/master/Distribution/XmlSchemas#install-globally-to-all-projects-on-your-machine-manually)

**Comment by jimfoye** [comment]
Thanks! I can wait a few days :+1:
