### ISSUE TITLE
Mandatory to have 2 logging config files for 32 and 64 architectures?

### ISSUE THREAD

**Issue by mcarlospc** [Excel-DNA/ExcelDna#284]
I don't know if this is necessarily a bug or if it works like this by design but I have to maintain 2 .config files with logging config for the 32 version and 64 version for it to work on both cases.

If my app name is SampleApp I have to maintain SampleApp-Addin.xll.config AND SampleApp-Addin64.xll.config for it to work on both architectures.

**Comment by caioproiete** [comment]
Hey @mcarlospc, this is by design and follows [Microsoft's standard for application configuration files](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/#application-configuration-files) where the name of the configuration file is the name of the app with a `.config` extension. For example, an app called `myApp.exe` should have a source configuration file called `myApp.exe.config`.

`SampleApp-AddIn.xll` and `SampleApp-AddIn64.xll` are effectively two separate apps/entry points that may or may not be deployed together (e.g. If all of your users have 64-bit Excel, you don't have to deploy the 32-bit version of the add-in) and therefore have separate configuration files.

**Comment by mcarlospc** [comment]
Thanks for the clarifications @caioproiete , we can close this issue then.
