### ISSUE TITLE
References break in ExcelDna.Registration when using ExcelDna.Integration v1.1.0-beta1

### ISSUE THREAD

**Issue by drobertson123** [Excel-DNA/ExcelDna#306]
My application requires a signed version of ExcelDNA.Integration so I tried upgrading to the v1.1.0-beta1 release on Nuget.

As soon as I did that I started getting errors. I am using the registration library to manually register functions;

registrations.Where(X => X.FunctionAttribute.Name == "XXXXXXXXX").RegisterFunctions();

Every reference to 'FunctionAttribute'  now shows the following error;
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'ExcelFunctionAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'ExcelDna.Integration, Version=1.0.7056.37028, Culture=neutral, PublicKeyToken=null'.	XXXXX.DataConnect.AddIn	C:\Users\XXXXX\source\repos\XXXXX-DataConnect\XXXXX.DataConnect.AddIn\Functions.cs	20	Active
`

I am currently using;

ExcelDna.Registration    v1.0.0.0
ExcelDna.IntelliSense    v1.2.0.0
ExcelDna.Integration     v1.1.0.0

**Comment by caioproiete** [comment]
Thanks @drobertson123 

This is kind of a chicken-and-egg problem. We needed to release a signed version of `ExcelDna.Integration` first, before we could update `ExcelDna.Registration` to reference it.

This particular issue you're reporting is fixed by PR Excel-DNA/Registration#28.

Of course, given the viral nature of strong-naming, we'll have to strong-name sign the `ExcelDna.Registration` library as well, which is done via PR Excel-DNA/Registration#29.

Once they both get merged, and we release a new version of `ExcelDna.Registration`, you should be all set (after you upgrade to the latest `ExcelDna.Registration` ).

The same goes for `ExcelDna.IntelliSense` (More PRs to follow).

**Comment by drobertson123** [comment]
Great, I was just about to report a similar symptom on the ExcelDna.IntelliSense project. I will hold off on creating that issue since you already have it on your plan.

Any idea when these will be pushed out to NuGet? I hate to be that guy but I am stuck waiting on deployment until these are sorted.

I appreciate your efforts, thanks.

**Comment by govert** [comment]
@caioproiete If you'd like to go ahead with the NuGet packages that would be great.
Otherwise I can have a look over the weekend.

**Comment by caioproiete** [comment]
@govert Alright. I'll do that tonight.

**Comment by caioproiete** [comment]
Pre-release NuGet packages referencing `ExcelDna.Integration` **v1.1.0-beta1** with assemblies strong-named (1) published to nuget.org:

- **ExcelDna.Registration**
  - [ExcelDna.Registration](https://www.nuget.org/packages/ExcelDna.Registration/) v1.1.0-beta1
  - [ExcelDna.Registration.VisualBasic](https://www.nuget.org/packages/ExcelDna.Registration.VisualBasic/) v1.1.0-beta1
  - [ExcelDna.Registration.FSharp](https://www.nuget.org/packages/ExcelDna.Registration.FSharp/) v1.1.0-beta1
- **ExcelDna.IntelliSense**
  - [ExcelDna.IntelliSense](https://www.nuget.org/packages/ExcelDna.IntelliSense/) v1.3.0-beta1

---

(_1_) `ExcelDna.Registration.FSharp` was not strong-name signed due to a bug in the FSharp compiler. See PR Excel-DNA/Registration#29 for details.

**Comment by drobertson123** [comment]
@caioproiete I have loaded the new assemblies from Nuget and so far everything looks good. I will update if I see any issues.

I wanted to say thanks for you pushing this out so fast. My butt was kind of on the line since the assembly signing issue was blocking a deploy and my director had a lot of focus on this project.

I know you rarely get any insight into how this is used but your fix is allowing me to deploy an Excel Addin that is used to monitor renewables power generation across North America. We expect the Addin to be deployed to roughly 4000 systems company-wide over the next few weeks.

This is good work and we appreciate it.
