### ISSUE TITLE
Pack NMath into .xll file

### ISSUE THREAD

**Issue by halirutan** [Excel-DNA/ExcelDna#332]
Attention: C# noob here! I have a [small project](https://github.com/halirutan/CIEDE2000-Color-Difference) that does some calculations and it uses [NMath](https://www.centerspace.net/nmath) for finding some roots. It works as expected during debugging, but I seem to be unable to provide a single, packed .xll file for the user. I tried to add `NMath.dll` as a reference to the `.dna` file, but it did not help.

I checked the [ExcleDna packaging docs](https://docs.excel-dna.net/exceldna-packing-tool/) and it has a limitations passage that reads

> Mixed code assemblies (that contain both managed and native code) cannot currently be packed.

In the `Release` directory of the project, I see a `64` folder that contains what I assume are native libraries like `libgfortran` that appear to be needed by NMath.

My questions are:

1. Am I right that the limitation applies to my project and I cannot distribute a packed `.xll` file to another user?
2. What is the correct way give the Excel AddIn then? I tried copying the whole Release folder to my AddIn folder and this worked. Will this also work on other (non-develop) machines?

**Comment by raymondjstone** [comment]
For this I would use a WIX packaged installer with the native libraries marked as pack=false in the DNA file and with code in the installer to setup the excel OPEN key.

**Comment by augustoproiete** [comment]
@halirutan `ExcelDnaPack` does not currently support packing of native libraries (see #331 and #329 for more details) which means you can't use the default way of packing everything into a single `.xll` file.

A common way to work around this issue and provide a single `.xll` to your users, is to embed native DLLs inside of your .NET DLL (which will be packed into the `.xll`) and extract it yourself to the same folder where the `.xll` is when the add-in starts.

However, in your case these NMath DLLs are very large (200+ MB) which would make the build process very slow as well as starting Excel would also be slowed down by the loading of the large add-in assembly and extracting the native DLLs to disk.

You could consider using a different library that doesn't require native DLLs so that everything can be packed into a single `.xll` without extra work. Maybe [Math.net](https://www.mathdotnet.com) has similar capabilities for the calculations you need?

@raymondjstone's suggestion also seems like a good alternative, in that you don't have to pack anything and distribute your add-in via an installer that takes care of deploying all the files needed for your add-in to run.

**Comment by halirutan** [comment]
Thank you both for your suggestions. As it turns out, I already looked into alternatives to NMath earlier today and found Math.net which also has root-finding methods. @augustoproiete is right that the NMath dependencies are rather large and I will see that I can switch libraries. Thanks again, I'm closing this as I have several clears ways how I can move forward.
