### ISSUE TITLE
Custom function custom error message?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [Excel-DNA/ExcelDna#341]
Currently our add-in is just catches any exception and returns a custom error message as a string in the global handler.

However, Excel's IFERROR() functions do not work with that approach.

With the new addin JS API, it seems possible to both return an error and set a custom message upon hover: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-errors

Is it possible to do so with ExcelDna?

**Comment by govert** [comment]
I don't the xll add-ins have access to this new error-comment feature of the JavaScript API.

The closest you might come is to schedule a macro using ExcelAsyncUtil.QueueAsMacro to set a note in the cell. This could have side effects like overriding an existing note, clearing the user's undo stack, or crashing because the reference is no longer valid, so it's not very safe.

You'd call some code like this in the exception handler:

```
            ExcelReference caller = XlCall.Excel(XlCall.xlfCaller) as ExcelReference;
            ExcelAsyncUtil.QueueAsMacro(() =>
                XlCall.Excel(XlCall.xlfNote, "Bad things happened here!", caller));
```

**Comment by wh1t3cAt1k** [comment]
Thank you @govert .
