### ISSUE TITLE
[Question] is it possible to produce a "fat" dll ?

### ISSUE THREAD

**Issue by akasolace** [Excel-DNA/ExcelDna#342]
Using the pack feature it is possible to produce a standalone xll used for distribution. Is it possible to generate similarly a "fat" dll which include all dlls dependencies also in order to facilitate distribution?

thank you

**Comment by raymondjstone** [comment]
You can add anything you want DLL wise into the pack so long as you don't mix assembly types, so for me this meant I could have C# stuff but not also include a C++ dll

**Comment by akasolace** [comment]
>You can add anything you want DLL wise into the pack so long as you don't mix assembly types, so for me this meant I could have C# stuff but not also include a C++ dll



@raymondjstone thank you for your message but just to clarify. I have a csharp project to create myAddin.xll and let say my project refers extLib.dll.  I know I can pack extLib.dll inside my xll for distribution. Now I would like to know if I can have a myAddin.dll which also bundles extLib.dll ? 

The reason for this is that my project is used both from Excel and from Python. Distribution for Excel is perfectly fine via the xll but the distribution for python is ennoying as I have to distribute all the referenced dlls on top of mine. I did not find out how to have a fat myAddin.dll that would bundles all dependencies. If you think this is feasible and could point me into the right direction this would be fantastic !

**Comment by govert** [comment]
There are tools for merging managed assemblies - e.g. ILMerge. Excel-DNA has nothing that will help in this regard.

**Comment by augustoproiete** [comment]
A couple of alternatives for merging .NET assemblies would be [ILRepack](https://github.com/gluck/il-repack) (_which is meant to replace ILMerge_), and [Costura.Fody](https://github.com/Fody/Costura) which is similar.

On a separate note, I'd recommend separating your functions in a more generic assembly, that can be re-used by Python, rather than exposing your ExcelDna assembly directly (and with it, bringing the dependency on `ExcelDna.Integration`). This will also help you design your functions in a way that is not dependent on Excel-DNA features, so that it can run smoothly outside of Excel.

So instead of this (which seems to be what you have at the moment):

![image](https://user-images.githubusercontent.com/177608/87988289-768c8280-cab6-11ea-962d-ca62e0d53200.png)

You'd have something like this:

![image](https://user-images.githubusercontent.com/177608/87988329-83a97180-cab6-11ea-8065-85a21cfd71f8.png)

You'd then use ILMerge/ILRepack/Fody.Costura/etc. in your `Functions` assembly to merge its dependencies, and your Python app would re-use the `Functions` without anything Excel-DNA related.

**Comment by akasolace** [comment]
@augustoproiete it seems indeed the right approach .... thank you for your inputs

**Comment by akasolace** [comment]
implementing the suggestion made by @augustoproiete and using ILmerge solved my issue.
