### ISSUE TITLE
Cannot debug my functions from VS and other questions

### ISSUE THREAD

**Issue by johnnyontheweb** [Excel-DNA/ExcelDna#379]
Hello,
I followed tutorials to include Excel-DNA starting from a .NET Framework library. I have a function like this:
```
Imports ExcelDna.Integration

Public Class tools
    <ExcelFunction(Description:="GG function")>
    Public Shared Function GGtest() As Double
        Return "test"
    End Function
End Class
```

I can see the function in Excel, but if I set a breakpoint in `Return` line, debugger won't stop. Is debug possible?
Am I missing something to set?
EDIT: I forgot to mention that in Excel I can see the function from auto-completion feature, but it displays a random number instead of the string!
See also:
[https://stackoverflow.com/questions/60627305/c-sharp-excel-dna-debugging](https://stackoverflow.com/questions/60627305/c-sharp-excel-dna-debugging)

In addition, some other questions:
1- which are exactly the requisites for a function to be seen from Excel-DNA? To be static (shared) and to be public and to have `<ExcelFunction(Description:="GG function")>` property I guess. If this is so, a second class having functions with this attribute will be seen in Excel?
2- is VB modules supported? they host shared function.
3- I tried to compile my DLL in 2 machines, one with Excel at 64bit and the other having 32bit. Is it compulsory to leave the DLL configuration to AnyCPU for compilation? This is not trivial, because one cannot check if the -packed.xll files are good for both 32 and 64 bit Excel using a single PC.
4- I read about the need to design the RibbonUI (if used) from VSTO and the import XML. I noticed also that nuget has a Excel-DNA Ribbon package - does it help to design the ribbon directly in VS?

Thanks in advance (I read some documentation and articles on these topics, but most of them are out-of-date and give confusing or non-working answers)

**Comment by govert** [comment]
Hi @johnnyontheweb 

Indeed debugging should work without issues for Excel-DNA functions.

Your function is problematic, since it is declared to return `Double` but actually returns a `string`. It might be that the compiler is not showing you the error, or that your add-in is not actually rebuilding. I would expect an error.

When calling the function from Excel, you need to put brackets behind the function name for it to be called. I.e. you have to call it as `=MyFunction()` and not just as `=MyFunction`. If this wrong, then you'll get a number which is the Excel RegistrationId for the function. Since the function is never actually called, that also explains why the debugger doesn't kick in.

Not sure if anything else is wrong with your debugging - you might post the build output and debug settings page for the project.

Regarding your other questions:
1. By default, Excel-DNA will register every `Public Shared` functions in a `Public Class` and `Public Functions` in a `Public Module` that has a friendly signature - basically primitive number types, `string`, `bool` and `Double(,)` and `Object(,)` arrays. ('Sub's are also registered as hidden macros, but that's another story).
2. Yes - VB  `Modules` work great.
3. The AnyCPU / 32bit / 64bit setting for the project will not make any difference. By default Excel-DNA will put a 32-bit and a 64-bit add-in the output directory (as well as 'packed' single-file versions). Both the normal and the 'packed' .xll files are bit-specific, so you have to run the right one to match the Excel bitness. Otherwise Excel will complain that the file format is not recognized (you can check this on your machine by double-clicking the wrong one).
4. You don't have to design the ribbon in VSTO at all - normally writing the xml by hand is quite easy. There are several examples and videos for making ribbons. Start here: https://github.com/Excel-DNA/Tutorials/tree/master/Fundamentals/RibbonBasics and here https://www.youtube.com/watch?v=2oBQaQFgQow

Indeed the documentation for Excel-DNA is not good enough yet - it's not something I like working on. But I try to give good support. My preferred channel for general and getting started support is the Google group https://groups.google.com/g/exceldna

**Comment by johnnyontheweb** [comment]
Thanks for the reply, and sorry for the copy-paste error, of course it is `Public Shared Function GGtest() As String`, not Double.
The point was about the `( )` at the end of the function. The number I saw earlier was RegistrationId, good to know.

All the replies are very clear, now I understand what's happening, thanks!
