### ISSUE TITLE
Nuget package from code

### ISSUE THREAD

**Issue by johnnyontheweb** [Excel-DNA/ExcelDna#382]
I'm trying to use 1.2.5-preview version, How to use the compiled DLLs?
Without nuget package I'm a little bit lost... could you provide some instructions?
How to get nuget package from code?

**Comment by govert** [comment]
@johnnyontheweb Are you getting an error when making an add-in that uses the ExcelDna.AddIn v 1.2.5-preview package?

**Comment by johnnyontheweb** [comment]
Yes, I'm using 1.2.5-preview to be able to call RTD from worksheet, as I read in [this ](https://groups.google.com/g/exceldna/c/4DaVCSlcpqo/m/dOkGheiWAgAJ)Google Groups thread.
For instance, using RTDClockVB sample project, if I write into a cell `=RTD("rtdclockvb.clockserver",,"")` I get `#N\D` (Excel is in Italian, the true call is `=DATITEMPOREALE("rtdclockvb.clockserver";;"")` ).
`=dnaRtdClock_ExcelRtdServer()` continues to work properly, but I need to use RTD function.

**Comment by govert** [comment]
Configuring Excel-DNA to provide the direct RTD server (so that you can use the built-in =RTD(...) function) is quite difficult.
This is because the COM registration must be done differently.
It is much easier if you make your own wrapper function like the `dnaRtdClock_ExcelRtdServer`.

If you want to try to make a server that provides the RTD directly, you need to have at least the following:
* Add an explicit `<ProgId(...)>` attribute to the RTD Server class
* Call `ComServer.DllRegisterServer()` in the AutoOpen implementation.

I'm not sure what else is needed there, as it is not the usual way of using the Excel-DNA RTD feature.

**Comment by johnnyontheweb** [comment]
This is exactly what I did. Maybe I didn't understand well, but it seems that it could work (as I read [here](https://groups.google.com/g/exceldna/c/4DaVCSlcpqo)). Ok, thanks anyway

**Comment by govert** [comment]
If you want to dig deeper, we can arrange a support session to look at your problem. You can arrange by emailing me directly.
