### ISSUE TITLE
Platforms in build process

### ISSUE THREAD

**Issue by davidhunter22** [Excel-DNA/ExcelDna#386]
Hi, I am new to Excel-DNA so sorry if I just can't find stuff yet.

I am wondering about the build platforms in the build process. Currently I see
AnyCPU
Mixed Platforms
Win32
x64
x86
I am wondering if this is deliberate and if the purpose of these is documented anywhere? I sort of suspect they may be at least in part accidental given both Win32, and x86.

I am sadly very familiar with building visual studio solutions with mixed C++/C#, well in our case C++/CLI projects. Visual Studio does a very poor job at this, for instance it will magically create platforms without you asking if you don't stop it doing so.
In general is there a specific place to discuss build issues? There seems to be a lot of issues specifically around SDK style project migration but that seems to be done. I ask as I would like to contribute and already have a few suggestions.

**Comment by govert** [comment]
Hi @davidhunter22 

It's good to distinguish the situation for building the Excel-DNA binaries themselves, vs building an add-in with Excel-DNA.

For building the Excel-DNA binaries, the platforms in the solution are indeed a bit messed up - my last attempt at clean-up was not able to make progress. It's not easy to end up with only one of Win32 and x86. There is also a project to host the .NET core part, which is not pushed to the public GitHub yet. In practice this has not really been a problem.
As you point out, the managed projects in the Excel-DNA binaries have all moved to SDK-style project files.

For building an Excel add-in with Excel-DNA, you should not have these platform problems. But here the SDK-style projects are still an unresolved problem, due to the NuGet package and build script needing changes to deal with the PackageReference style NuGet imports. Most of the GitHub issues related to SDK style projects are related to this work, which has not been started.

If you want to contribute to Excel-DNA that would be very welcome, However, for the core Excel-DNA binaries repository, I suggest you take it a bit slow and check that I'm ready for your changes. I've been quite cautious in accepting contributions here, to make sure I'm able to support the project over the long term. It helps me most if you could make an issue where we can discuss your suggestions before you open a pull request.

**Comment by davidhunter22** [comment]
Hi, Yes I meant building Excel-DNA itself rather than using it. 
I was not going to start lobbing stuff at you! So assuming you are OK with looking at a change after a discussion do you prefer people fork,  do changes in their own github account so that you can look at them or do you prefer people do that and then do a PR athat can be discussed/rejected?
In particular on the x86/Win32 thing I believe I could fix that pretty easily.
For x64/x86/AnyCPU do you have a particular ideal state in mind. There are generally two main ways I have seen
1) Build C# AnyCPU, build C++ x86/x64 
2) Build everything x86 and x64 with no AnyCPU
The second is much simpler and easier IMO easier to understand although sometimes a bit confusing for C# only people.

**Comment by govert** [comment]
I don't know how the platform interacts with the managed projects. I would prefer not to have platform-specific output directories for the managed projects, as we already have the two TargetFramework-specific outputs to deal with.

I suggest you make a pull request and I can see how things would look.

**Comment by govert** [comment]
Thank you @davidhunter22 - I've pulled in your changes.

**Comment by davidhunter22** [comment]
Great.

Do you want me to make a similar set of changes for the new C++ project. If so would you prefer smaller PR's or one bigger one?

**Comment by govert** [comment]
I've tried to make the MASM target change and clean up the post-build step.
If you would like to suggest further changes I'm happy to have a look.
