### ISSUE TITLE
Add ExcelDna.IntelliSense.xll in .dna file

### ISSUE THREAD

**Issue by aboah** [Excel-DNA/ExcelDna#400]
Is it possible to deploy ExcelDna.IntelliSense.xll with pack=true in the .dna file

Again is it possible to install two or more .xll add-ins in one deployment scenario. How is it done

**Comment by govert** [comment]
Instead of deploying the complete intellisense .xll add-in, you can also deploy it as a library inside your add-in.

For this you would 

* Install the ExcelDna.IntelliSense NuGet package into your project.
* Then in your `AutoOpen / Close` implementations, add calls to `IntelliSenseSerer.Install / Uninstall`.
* Finally add a packing reference in your .dna file:
```
<Reference Path='ExcelDna.IntelliSense.dll' Pack='true' />
```

After doing this the IntelliSense should work the same without requiring the separate add-in.
