### ISSUE TITLE
Assembly version number wasn't updated for version 1.5.0

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#412]
It's still 1.1.0.0:
```
    <Reference Include="ExcelDna.Integration, Version=1.1.0.0, Culture=neutral, PublicKeyToken=f225e9659857edbe, processorArchitecture=MSIL">
       <HintPath>..\packages\ExcelDna.Integration.1.5.0\lib\net452\ExcelDna.Integration.dll</HintPath>
     </Reference>
```

**Comment by augustoproiete** [comment]
This is by design. The `AssemblyVersion` is frozen between minor releases to avoid issues with binding redirects ever since we started signing assemblies with a strong name.

More information here: https://github.com/Excel-DNA/ExcelDna/pull/250#issuecomment-508945844

When ExcelDna v2.0.0 is released, we'll change the `AssemblyVersion` to `2.0.0.0` and it will be frozen again for minor releases that follow. i.e. It's always `{Major}.0.0.0`
