### ISSUE TITLE
Exceptions about referencing collectible assemblies from non-collectible ones

### ISSUE THREAD

**Issue by kolkhi** [Excel-DNA/ExcelDna#450]
Hello, 

I have a problem when using DevExpress libraries in the .NET 6 version of the ExcelDna add-in. The add-in contains a Ribbon toolbar with buttons and I want to show some dialog forms when the user clicks those buttons, but I'm getting
the following exceptions:
 
	1. A non-collectible assembly may not reference a collectible assembly.

	2. Resolving to a collectible assembly is not supported.
	
Attached is the test case, where both issues can be reproduced (click "Button 1" for exception 1 and "Button 2" for exception 2).
[Ribbon.zip](https://github.com/Excel-DNA/ExcelDna/files/8505085/Ribbon.zip).

**Comment by govert** [comment]
I don't have the DevExpress tools, so I can't build your project at this stage.
But maybe you should ask them for some support on this.

What I think is going on is that Excel-DNA is making an "AssemblyLoadContext" for your add-in and it is marked as 'collectible'. 
See some background information here https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext and  the Excel-DNA code here https://github.com/Excel-DNA/ExcelDna/blob/2d00e946b8ea7f9828f208457da91d527e7ed64b/Source/ExcelDna.ManagedHost/ExcelDnaAssemblyLoadContext.cs#L10.
Your assembly is loaded into this AssemblyLoadContext and then tries to load the DevExpress libraries, which are raising the exceptions you show. It seems some DevExpress component is resolving your assembly, or another DevExpress dependency, and then failing because of some internal limitation.
It would be helpful if they can explain how serious this limitation is, whether there is a workaround etc.

From the Excel-DNA side it might be possible to make it possible to override the "isCollectible" flag in a configuration setting somehow. But I would prefer not to fiddle with that until we understand the issue a bit better.

I'm happy to help the DexExpress guys navigate the Excel-DNA code if they want to understand better what is going on, or try to answer other questions they might have.

**Comment by kolkhi** [comment]
Hello Govert,

Thanks for your response and provided details. I've opened a ticket regarding this issue in the DevExpress support - https://supportcenter.devexpress.com/ticket/details/t1084044/exceptions-about-referencing-collectible-assemblies-from-non-collectible-ones-when-using

**Comment by kolkhi** [comment]
Looks like some DevExpress libraries generate dynamic assemblies internally, which are marked as non-collectible. As I understand from their response, it's not possible to change this behavior without introducing 
some undesirable side effects (see more details here https://supportcenter.devexpress.com/ticket/details/t1084193/dynamically-generated-assemblies-throw-exceptions-when-loaded-in-certain-environments). 

I have questions regarding the **isCollectable** flag in the **ExcelDnaAssemblyLoadContext**:

1. Is it possible to add a setting in the configuration to override this flag?
2. If I set the flag to **false** in the Excel-DNA, what kind of issues this change may introduce?
