### ISSUE TITLE
Excel call on non-UI thread throws an exception

### ISSUE THREAD

**Issue by interdrift** [Excel-DNA/ExcelDna#6]
Running something like this on non-UI thread would cause Excel-Dna to throw an exception wihout any inner exception details.

            var addinPath = (string)XlCall.Excel(XlCall.xlGetName); // exception gets thrown over here.
            var addinDir = addinPath.Substring(0, addinPath.LastIndexOf('\\'));
            var configPath = @"Resources\config.xml";

            var filePath = Path.Combine(addinDir, configPath);

            return filePath;

**Comment by govert** [comment]
This is expected. Anything related to the C API (XlCall.Excel or ExcelReference) cannot be used on other threads.

You can transition to a macro context on the main thread by using 
```
    ExcelAsyncUtil.QueueAsMacro(() => 
    {
        // Do stuff here which must run on the meain thread a s macro
    }
```

It should be possible to check whether a failure of `XlCall.Excel` is due to this reason, and add more meaningful exception details.

**Comment by govert** [comment]
If you just want to get the path of the .xll, you can probably call `ExcelDnaUtil.XllPath` from any thread.

**Comment by interdrift** [comment]
Okay,great thanks. I will see if I can add some details to the error.
