### ISSUE TITLE
Can PackedXLL Registered on UOS

### ISSUE THREAD

**Issue by zzzqgrelax** [Excel-DNA/ExcelDna#718]
I recently took a look at the Excel addin for the competing company's  on UOS system.
The basic situation is like this, this plugin is loaded in Kingsoft WPS, so can only use WPSJS technology, just like Microsoft OFFICEJS, wpsjs itself does not support UDF, but can register through RegisterXLL（wps.Application.RegisterXLL("/***/lib/aaa.xll"),）
we know that the xll should be written in C++. I wonder if I can achieve the same effect with ExcelDNA
I look forward to your help.

I haved try that
on windows   register my xll（.NET 4） OK 
on windows   register my xll（.NET 6） got error 
![image](https://github.com/user-attachments/assets/2da958a1-ec24-4bd4-a2be-d437312e9a9e)

**Comment by zzzqgrelax** [comment]
only need udf  in xll

**Comment by keithalewis** [comment]
Have you looked at my library https://github.com/xlladdins/xll? It uses only C++.
我不知道 if you can just open a xll in Kingsoft WPS on UOS.

**Comment by zzzqgrelax** [comment]
@keithalewis  I have tried your library     
on windows your library is OK    but on UOS  i can't open a xll in WPS  with your test.xll   but competing company's xll works    
i really dont know how it works now

**Comment by keithalewis** [comment]
How was competing company's xll built?

**Comment by govert** [comment]
Under .NET Framework we are able to load the initial Excel-DNA loader assembly from memory. 

Under .NET core that is not possible, so we extract it to a temp folder and load from there. It seems like this extract step fails. The code triggering for the error display is here:
https://github.com/Excel-DNA/ExcelDna/blob/1dadf441ee8ea55024a87898ed02ba4f45d6aa77/Source/ExcelDna.Host/host.cpp#L363
coming from this function here: https://github.com/Excel-DNA/ExcelDna/blob/1dadf441ee8ea55024a87898ed02ba4f45d6aa77/Source/ExcelDna.Host/host.cpp#L331
with more here
https://github.com/Excel-DNA/ExcelDna/blob/1dadf441ee8ea55024a87898ed02ba4f45d6aa77/Source/ExcelDna.Host/host.cpp#L101
and code for managing the temp files here
https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Host/TempDir.cpp

You might inspect the code around these areas to recognize some call that is not supported on your platform.
Otherwise, you might need to set up a debugger or make custom Excel-DNA versions to track the exact line that is a problem.
