### ISSUE TITLE
ExcelDna.xll missing from nuget package

### ISSUE THREAD

**Issue by gigi81** [Excel-DNA/ExcelDna#74]
Hi,
I just installed nuget package ExcelDna.AddIn.0.33.9 and the file Excel.xll and Excel64.xll are missing from the tools folder.
When trying to run the ExcelDnaPack the following error is returned:
Base add-in not found.

**Comment by govert** [comment]
Are you saying those files were not extracted into packages\ExcelDna.AddIn.0.33.9\tools\... ?

Perhaps you have some anti-virus software blocking it?

Otherwise you can download and extract the package from the NuGet site directly:
https://www.nuget.org/api/v2/package/ExcelDna.AddIn/0.33.9
(the .nupkg file is just a .zip file).

**Comment by gigi81** [comment]
Hi @govert.
I reinstalled the package and the files are now there... not sure what happened. Might be a antivirus as you suggested. Closing the issue. Many thanks for the quick reply.
