### ISSUE TITLE
UnhandledExceptionHandler only handles Exceptions on Methods with Return type?

### ISSUE THREAD

**Issue by robodude666** [Excel-DNA/ExcelDna#90]
I'm noticing that if I register an `UnhandledExceptionHandler` via:

```
ExcelIntegration.RegisterUnhandledExceptionHandler(ErrorHandler);
```

and an exception occurs within my `ExcelFunction`-marked method the handler does not trigger unless the return type is not `void`.

Is this intentional, or a bug?

**Comment by govert** [comment]
You're right about what it does.

Perhaps it should be called `RegisterUnhandledFunctionExceptionHandler`?

**Comment by robodude666** [comment]
Might be better to provide documentation in intellisense (and elsewhere) that highlights this expected behavior. You can still have a void function; not everyone is familiar with Visual Basic's version of Function vs Sub.

Is there a technical limitation on why it can't handle exceptions from void?

**Comment by caioproiete** [comment]
+1 to both suggestions.

@govert: If you'll consider giving the method a better name, I'd also suggest you change it to be an event, instead of a method call, such as:

```
ExcelIntegration.UnhandledFunctionException += ExcelUnhandledFunctionException;
````

It's more natural as it aligns with the way these handlers are registered in WinForms and WPF (which devs are used to)... For example:

```
// Any app
AppDomain.CurrentDomain.UnhandledException += AppDomainUnhandledException;
TaskScheduler.UnobservedTaskException += TaskSchedulerUnobservedTaskException;

// WinForms specific
Application.ThreadException += ApplicationThreadUnhandledException;

// WPF specific
Dispatcher.CurrentDispatcher.UnhandledException += DispatchedUnhandledException;
```

--

@robodude666: I'm curious with the use-case. Could you give an example where you find that using an Excel function that returns void is useful (from a user's perspective)?

**Comment by govert** [comment]
The exception handler gets woven into the IL method stub, which is not code I'm likely to fiddle with at this stage.

I think I didn't make it an event since it needs to return the overridden result of the function. (I guess the event signature could have an `out` or `ref` parameter for that purpose, but maybe that didn't occur to me at the time.)

I'm not likely to make any changes to this aspect of Excel-DNA except improved documentation.

**Comment by govert** [comment]
I've implemented the call to the UnhandledExceptionHandler from macros. I would appreciate any help with testing, both for any regression and that this particular issue is fixed. I've updated the source, and pushed to NuGet as ExcelDna.AddIn version 0.35.1-beta2. Any feedback appreciated.
